# Theme file (default theme)
# This file specifies the main theme of the visual representation. All
# specifications provided here may be altered using the configuration file.
#
# This theme requires fonts that support utf-8, colors, and emojis.

if [ ! "${THEME_LOADED:-}" ]; then
  # Colors (internal only)
  ESC=$(printf '\033')
  BOLD="${ESC}[1m"
  FAINT="${ESC}[2m"
  ITALIC="${ESC}[3m"
  UNDERLINE="${ESC}[4m"
  CARTIST="${ESC}[38;5;209m"
  CTITLE="${ESC}[38;5;229m"
  CRELINFO="${ESC}[38;5;179m"
  CYEAR="${ESC}[38;5;179m"
  CDISAMB="$FAINT${ESC}[38;5;172m"
  CNOTE="${ESC}[38;5;242m"
  CXXX="${ESC}[38;5;109m"
  CDESC="${ESC}[38;5;254m"
  CPURPLE="${ESC}[38;5;213m"
  CKB="${ESC}[38;5;224m"
  OFF="${ESC}[m"

  # Pointers
  # ========
  # Sign that indicates the existence of audio files
  FORMAT_LOCAL="${FORMAT_LOCAL:-"🔆"}"
  export FORMAT_LOCAL

  # Input prompt
  # =============
  # General search prompt (for now only used when choosing one-of-many artist)
  SEARCH_PROMPT=${SEARCH_PROMPT:-"🔎 〉"}
  export SEARCH_PROMPT

  # General workings of format strings
  #
  # A format string (_FMT) contains placeholders, e.g., <<name>>. These
  # placeholders are filled with the relevant information. A placeholder may
  # occur zero times, once, or more than once. There are two types of
  # placeholders: strings and items. A placeholder of type string comes with a
  # variable containing a `printf` expression (_FMT_placeholder). This `printf`
  # expression may be used to additionally modify the string passed. If the
  # string passed is empty, then each corresponding placeholder is replaced
  # with the empty string, i.e., the `printf` expression is bypassed. A
  # placeholder of the alternative type (item) comes with a series of variables
  # that encode constants to be used (_FMT_placeholder_XYZ).
  #
  # The items in the format string may be separated with "\t". This will induce
  # a proper representation (using `column`). By default, all fields but the
  # first are left aligned, and the first field is right aligned. This can be
  # changed by setting the appropriate FMT_RIGHTALIGN variable. If that
  # variable is empty, then the first field is right aligned. This means that
  # at least one field must be right aligned.
  #
  # Artist view
  # ===========
  # <<flag>>            item    Indication for locally available audio files
  # <<type>>            item    Indicator for single-person artist or group
  # <<name>>            string  Artist name
  # <<disambiguation>>  string  Disambiguation string
  #
  AV_FMT="${AV_FMT:-"<<flag>>\t<<type>> <<name>> <<disambiguation>>"}"
  AV_FMT_CNT=$(($(printf "$AV_FMT" | tr -cd '\t' | wc -c) + 1))
  AV_FMT_RIGHTALIGN="${AV_FMT_RIGHTALIGN:-"1"}"
  AV_FMT_FLAG_LOCAL="${AV_FMT_FLAG_LOCAL:-"$FORMAT_LOCAL"}"
  AV_FMT_FLAG_NO_LOCAL="${AV_FMT_FLAG_NO_LOCAL:-""}"
  AV_FMT_TYPE_PERSON="${AV_FMT_TYPE_PERSON:-🧑‍🎤}"
  AV_FMT_TYPE_GROUP="${AV_FMT_TYPE_GROUP:-🧑‍🤝‍🧑}"
  AV_FMT_NAME="${AV_FMT_NAME:-"${CARTIST}%s${OFF}"}"
  AV_FMT_DISAMBIGUATION="${AV_FMT_DISAMBIGUATION:-"${CDISAMB}(%s)${OFF}"}"
  export AV_FMT AV_FMT_CNT AV_FMT_RIGHTALIGN AV_FMT_FLAG_LOCAL \
    AV_FMT_FLAG_NO_LOCAL AV_FMT_TYPE_PERSON AV_FMT_TYPE_GROUP AV_FMT_NAME \
    AV_FMT_DISAMBIGUATION

  # Release-group view
  # ==================
  # <<flag>>          item    Indication for locally available audio files
  # <<type>>          item    Indicates the type
  # <<hassecondary>>  item    Indicates if there is some secondary type or none
  # <<secondary>>     string  List of secondary types
  # <<title>>         string  Title of album
  # <<artist>>        string  Artist of album
  # <<year>>          string  Year of initial release
  # Note: The above <<secondary>> is of a joint item-string type. See code for
  # details.
  RGV_FMT="${RGV_FMT:-"<<flag>>\t<<type>>\t<<hassecondary>>\t<<title>><<artist>> <<year>> <<secondary>>"}"
  RGV_FMT_CNT=$(($(printf "$RGV_FMT" | tr -cd '\t' | wc -c) + 1))
  RGV_FMT_RIGHTALIGN="${RGV_FMT_RIGHTALIGN:-"1"}"
  RGV_FMT_FLAG_LOCAL="${RGV_FMT_FLAG_LOCAL:-"$FORMAT_LOCAL"}"
  RGV_FMT_FLAG_NO_LOCAL="${RGV_FMT_FLAG_NO_LOCAL:-""}"
  RGV_FMT_TYPE_SINGLE="${RGV_FMT_TYPE_SINGLE:-"SI 🎶"}"
  RGV_FMT_TYPE_ALBUM="${RGV_FMT_TYPE_ALBUM:-"LP 💽"}"
  RGV_FMT_TYPE_EP="${RGV_FMT_TYPE_EP:-"EP 📀"}"
  RGV_FMT_TYPE_BROADCAST="${RGV_FMT_TYPE_BROADCAST:-"BR 📻"}"
  RGV_FMT_TYPE_OTHER="${RGV_FMT_TYPE_OTHER:-"OT ❔"}"
  RGV_FMT_TYPE_UNKNOWN="${RGV_FMT_TYPE_UNKNOWN:-""}"
  RGV_FMT_HASSECONDARY_YES="${RGV_FMT_HASSECONDARY_YES:-"☼"}"
  RGV_FMT_HASSECONDARY_NO="${RGV_FMT_HASSECONDARY_NO:-""}"
  RGV_FMT_SECONDARY="${RGV_FMT_SECONDARY:-"${CNOTE}[☼: %s]${OFF}"}"
  RGV_FMT_SECONDARY_COMPILATION="${RGV_FMT_SECONDARY_COMPILATION:-"🧩 compilation"}"
  RGV_FMT_SECONDARY_SOUNDTRACK="${RGV_FMT_SECONDARY_SOUNDTRACK:-"🎬 soundtrack"}"
  RGV_FMT_SECONDARY_SPOKENWORD="${RGV_FMT_SECONDARY_SPOKENWORD:-"📖 spokenword"}"
  RGV_FMT_SECONDARY_INTERVIEW="${RGV_FMT_SECONDARY_INTERVIEW:-"💬 interview"}"
  RGV_FMT_SECONDARY_AUDIOBOOK="${RGV_FMT_SECONDARY_AUDIOBOOK:-"🎧 audiobook"}"
  RGV_FMT_SECONDARY_AUDIODRAMA="${RGV_FMT_SECONDARY_AUDIODRAMA:-"🎭 audio drama"}"
  RGV_FMT_SECONDARY_LIVE="${RGV_FMT_SECONDARY_LIVE:-"🎤 live"}"
  RGV_FMT_SECONDARY_REMIX="${RGV_FMT_SECONDARY_REMIX:-"🔁 remix"}"
  RGV_FMT_SECONDARY_DJMIX="${RGV_FMT_SECONDARY_DJMIX:-"🪩 DJ-mix"}"
  RGV_FMT_SECONDARY_MIXTAPE="${RGV_FMT_SECONDARY_MIXTAPE:-"📼 mixtape"}"
  RGV_FMT_SECONDARY_DEMO="${RGV_FMT_SECONDARY_DEMO:-"🧪 demo"}"
  RGV_FMT_SECONDARY_FIELDREC="${RGV_FMT_SECONDARY_FIELDREC:-"🌿 field recording"}"
  RGV_FMT_TITLE="${RGV_FMT_TITLE:-"${CTITLE}%s${OFF}"}"
  RGV_FMT_ARTIST="${RGV_FMT_ARTIST:-" — ${CARTIST}%s${OFF}"}"
  RGV_FMT_YEAR="${RGV_FMT_YEAR:-"${CYEAR}(%s)${OFF}"}"
  export RGV_FMT RGV_FMT_CNT RGV_FMT_RIGHTALIGN RGV_FMT_FLAG_LOCAL \
    RGV_FMT_FLAG_NO_LOCAL RGV_FMT_TYPE_SINGLE RGV_FMT_TYPE_ALBUM \
    RGV_FMT_TYPE_EP RGV_FMT_TYPE_BROADCAST RGV_FMT_TYPE_OTHER \
    RGV_FMT_TYPE_UNKNOWN RGV_FMT_HASSECONDARY_YES RGV_FMT_HASSECONDARY_NO \
    RGV_FMT_SECONDARY RGV_FMT_SECONDARY_COMPILATION \
    RGV_FMT_SECONDARY_SOUNDTRACK RGV_FMT_SECONDARY_SPOKENWORD \
    RGV_FMT_SECONDARY_INTERVIEW RGV_FMT_SECONDARY_AUDIOBOOK \
    RGV_FMT_SECONDARY_AUDIODRAMA RGV_FMT_SECONDARY_LIVE \
    RGV_FMT_SECONDARY_REMIX RGV_FMT_SECONDARY_DJMIX \
    RGV_FMT_SECONDARY_MIXTAPE RGV_FMT_SECONDARY_DEMO RGV_FMT_SECONDARY_FIELDREC \
    RGV_FMT_TITLE RGV_FMT_ARTIST RGV_FMT_YEAR

  # Release view
  # ============
  # <<flag>>      item     Indication for locally available audio files
  # <<status>>    item     Release status
  # <<tracks>>    string   Total number of track
  # <<media>>     string   Media description
  # <<year>>      string   Release year
  # <<country>>   string   Release country
  # <<label>>     string   Release label
  # <<title>>     string   Optional titel string
  # <<artist>>    string   Optional artist string
  RV_FMT="${RV_FMT:-"<<flag>>\t<<status>>\t<<tracks>>\t<<media>>\t<<year>>\t<<country>>\t<<label>>\t<<title>> <<artist>>"}"
  RV_FMT_CNT=$(($(printf "$RV_FMT" | tr -cd '\t' | wc -c) + 1))
  RV_FMT_RIGHTALIGN="${RV_FMT_RIGHTALIGN:-"1,3"}"
  RV_FMT_FLAG_LOCAL="${RV_FMT_FLAG_LOCAL:-"$FORMAT_LOCAL"}"
  RV_FMT_FLAG_NO_LOCAL="${RV_FMT_FLAG_NO_LOCAL:-""}"
  RV_FMT_STATUS_OFFICIAL="${RV_FMT_STATUS_OFFICIAL:-"🟢"}"
  RV_FMT_STATUS_PROMO="${RV_FMT_STATUS_PROMO:-"📣"}"
  RV_FMT_STATUS_BOOTLEG="${RV_FMT_STATUS_BOOTLEG:-"💣"}"
  RV_FMT_STATUS_PSEUDO="${RV_FMT_STATUS_PSEUDO:-"🌀"}"
  RV_FMT_STATUS_WITHDRAWN="${RV_FMT_STATUS_WITHDRAWN:-"🔙"}"
  RV_FMT_STATUS_EXPUNGED="${RV_FMT_STATUS_EXPUNGED:-"🧹"}"
  RV_FMT_STATUS_CANCELLED="${RV_FMT_STATUS_CANCELLED:-"❌"}"
  RV_FMT_STATUS_UNKNOWN="${RV_FMT_STATUS_UNKNOWN:-""}"
  RV_FMT_TRACKS="${RV_FMT_TRACKS:-"${CXXX}%s tracks${OFF}"}"
  RV_FMT_MEDIA="${RV_FMT_MEDIA:-"${CXXX}%s${OFF}"}"
  RV_FMT_YEAR="${RV_FMT_YEAR:-"${CYEAR}%s${OFF}"}"
  RV_FMT_COUNTRY="${RV_FMT_COUNTRY:-"${CYEAR}%s${OFF}"}"
  RV_FMT_LABEL="${RV_FMT_LABEL:-"${CARTIST}%s${OFF}"}"
  RV_FMT_TITLE="${RV_FMT_TITLE:-"${FAINT}as${OFF} ${CTITLE}%s${OFF}"}"
  RV_FMT_ARTIST="${RV_FMT_ARTIST:-"${FAINT}by${OFF} ${CTITLE}%s${OFF}"}"
  export RV_FMT RV_FMT_CNT RV_FMT_RIGHTALIGN RV_FMT_FLAG_LOCAL \
    RV_FMT_FLAG_NO_LOCAL RV_FMT_STATUS_OFFICIAL RV_FMT_STATUS_PROMO \
    RV_FMT_STATUS_BOOTLEG RV_FMT_STATUS_PSEUDO RV_FMT_STATUS_WITHDRAWN \
    RV_FMT_STATUS_EXPUNGED RV_FMT_STATUS_CANCELLED RV_FMT_STATUS_UNKNOWN \
    RV_FMT_TRACKS RV_FMT_MEDIA RV_FMT_YEAR RV_FMT_COUNTRY RV_FMT_LABEL \
    RV_FMT_TITLE RV_FMT_ARTIST

  # Recording view
  # ==============
  # <<flag>>       item     Indication for locally available audio files
  # <<media>>      string   Media identifier
  # <<nr>>         string   Track number within media
  # <<title>>      string   Track title
  # <<artist>>     string   Track artist
  # <<duration>>   string   Track duration
  REC_FMT="${REC_FMT:-"<<flag>>\t<<media>>\t<<nr>>\t<<title>>\t<<artist>>\t<<duration>>"}"
  REC_FMT_CNT=$(($(printf "$REC_FMT" | tr -cd '\t' | wc -c) + 1))
  REC_FMT_RIGHTALIGN="${REC_FMT_RIGHTALIGN:-"1,2,3"}"
  REC_FMT_FLAG_LOCAL="${REC_FMT_FLAG_LOCAL:-"$FORMAT_LOCAL"}"
  REC_FMT_FLAG_NO_LOCAL="${REC_FMT_FLAG_NO_LOCAL:-""}"
  REC_FMT_MEDIA="${REC_FMT_MEDIA:-"${CNOTE}${FAINT}%s${OFF}"}"
  REC_FMT_NR="${REC_FMT_NR:-"${CNOTE}%s${OFF}"}"
  REC_FMT_TITLE="${REC_FMT_TITLE:-"${CTITLE}%s${OFF}"}"
  REC_FMT_ARTIST="${REC_FMT_ARTIST:-"${CARTIST}%s${OFF}"}"
  REC_FMT_DURATION="${REC_FMT_DURATION:-"${CXXX}%s${OFF}"}"
  export REC_FMT REC_FMT_CNT REC_FMT_RIGHTALIGN REC_FMT_FLAG_LOCAL \
    REC_FMT_FLAG_NO_LOCAL REC_FMT_MEDIA REC_FMT_NR REC_FMT_TITLE \
    REC_FMT_ARTIST REC_FMT_DURATION

  # Recording view (playlist)
  # =========================
  # <<playing>>    item     Mark for currently playing track
  # <<title>>      string   Track title
  # <<artist>>     string   Track artist
  # <<duration>>   string   Track duration
  PLYLST_FMT="${PLYLST_FMT:-"<<playing>>\t<<title>>\t<<artist>>\t<<duration>>"}"
  PLYLST_FMT_CNT=$(($(printf "$PLYLST_FMT" | tr -cd '\t' | wc -c) + 1))
  PLYLST_FMT_RIGHTALIGN="${PLYLST_FMT_RIGHTALIGN:-"1"}"
  PLYLST_FMT_PLAYING_YES="${PLYLST_FMT_PLAYING_YES:-"👉"}"
  PLYLST_FMT_PLAYING_NO="${PLYLST_FMT_PLAYING_NO:-""}"
  PLYLST_FMT_TITLE="${PLYLST_FMT_TITLE:-"${CTITLE}%s${OFF}"}"
  PLYLST_FMT_ARTIST="${PLYLST_FMT_ARTIST:-"${CARTIST}%s${OFF}"}"
  PLYLST_FMT_DURATION="${PLYLST_FMT_DURATION:-"${CXXX}%s${OFF}"}"
  export PLYLST_FMT PLYLST_FMT_CNT PLYLST_FMT_RIGHTALIGN \
    PLYLST_FMT_PLAYING_YES PLYLST_FMT_PLAYING_NO PLYLST_FMT_TITLE \
    PLYLST_FMT_ARTIST PLYLST_FMT_DURATION

  # Headers
  # =======
  # These header strings are based on the respective view and its fields
  # defined above.
  #
  # Header that displays artist's name (based on artist view)
  HEADER_ARTIST_FMT="${HEADER_ARTIST_FMT:-"🎤\t<<name>> 〉"}"
  HEADER_ARTIST_FMT_CNT=$(($(printf "$HEADER_ARTIST_FMT" | tr -cd '\t' | wc -c) + 1))
  HEADER_ARTIST_FMT_RIGHTALIGN="${HEADER_ARTIST_FMT_RIGHTALIGN:-"1"}"
  HEADER_ARTIST_FMT_FLAG_LOCAL="${HEADER_ARTIST_FMT_FLAG_LOCAL:-"$AV_FMT_FLAG_LOCAL"}"
  HEADER_ARTIST_FMT_FLAG_NO_LOCAL="${HEADER_ARTIST_FMT_FLAG_NO_LOCAL:-"$AV_FMT_FLAG_NO_LOCAL"}"
  HEADER_ARTIST_FMT_TYPE_PERSON="${HEADER_ARTIST_FMT_TYPE_PERSON:-"$AV_FMT_TYPE_PERSON"}"
  HEADER_ARTIST_FMT_TYPE_GROUP="${HEADER_ARTIST_FMT_TYPE_GROUP:-"$AV_FMT_TYPE_GROUP"}"
  HEADER_ARTIST_FMT_NAME="${HEADER_ARTIST_FMT_NAME:-"$AV_FMT_NAME"}"
  HEADER_ARTIST_FMT_DISAMBIGUATION="${HEADER_ARTIST_FMT_DISAMBIGUATION:-"$AV_FMT_DISAMBIGUATION"}"
  export HEADER_ARTIST_FMT HEADER_ARTIST_FMT_CNT HEADER_ARTIST_FMT_RIGHTALIGN \
    HEADER_ARTIST_FMT_FLAG_LOCAL HEADER_ARTIST_FMT_FLAG_NO_LOCAL \
    HEADER_ARTIST_FMT_TYPE_PERSON HEADER_ARTIST_FMT_TYPE_GROUP \
    HEADER_ARTIST_FMT_NAME HEADER_ARTIST_FMT_DISAMBIGUATION

  # Header that displays the release-group (based on release-group view)
  HEADER_RG_FMT="${HEADER_RG_FMT:-"🎤\t<<artist>> 》<<title>> 〉"}"
  HEADER_RG_FMT_CNT=$(($(printf "$HEADER_RG_FMT" | tr -cd '\t' | wc -c) + 1))
  HEADER_RG_FMT_RIGHTALIGN="${HEADER_RG_FMT_RIGHTALIGN:-"1"}"
  HEADER_RG_FMT_FLAG_LOCAL="${HEADER_RG_FMT_FLAG_LOCAL:-"$RGV_FMT_FLAG_LOCAL"}"
  HEADER_RG_FMT_FLAG_NO_LOCAL="${HEADER_RG_FMT_FLAG_NO_LOCAL:-"$RGV_FMT_FLAG_NO_LOCAL"}"
  HEADER_RG_FMT_TYPE_SINGLE="${HEADER_RG_FMT_TYPE_SINGLE:-"$RGV_FMT_TYPE_SINGLE"}"
  HEADER_RG_FMT_TYPE_ALBUM="${HEADER_RG_FMT_TYPE_ALBUM:-"$RGV_FMT_TYPE_ALBUM"}"
  HEADER_RG_FMT_TYPE_EP="${HEADER_RG_FMT_TYPE_EP:-"$RGV_FMT_TYPE_EP"}"
  HEADER_RG_FMT_TYPE_BROADCAST="${HEADER_RG_FMT_TYPE_BROADCAST:-"$RGV_FMT_TYPE_BROADCAST"}"
  HEADER_RG_FMT_TYPE_OTHER="${HEADER_RG_FMT_TYPE_OTHER:-"$RGV_FMT_TYPE_OTHER"}"
  HEADER_RG_FMT_TYPE_UNKNOWN="${HEADER_RG_FMT_TYPE_UNKNOWN:-"$RGV_FMT_TYPE_UNKNOWN"}"
  HEADER_RG_FMT_HASSECONDARY_YES="${HEADER_RG_FMT_HASSECONDARY_YES:-"$RGV_FMT_HASSECONDARY_YES"}"
  HEADER_RG_FMT_HASSECONDARY_NO="${HEADER_RG_FMT_HASSECONDARY_NO:-"$RGV_FMT_HASSECONDARY_NO"}"
  HEADER_RG_FMT_SECONDARY="${HEADER_RG_FMT_SECONDARY:-"$RGV_FMT_SECONDARY"}"
  HEADER_RG_FMT_SECONDARY_COMPILATION="${HEADER_RG_FMT_SECONDARY_COMPILATION:-"$RGV_FMT_SECONDARY_COMPILATION"}"
  HEADER_RG_FMT_SECONDARY_SOUNDTRACK="${HEADER_RG_FMT_SECONDARY_SOUNDTRACK:-"$RGV_FMT_SECONDARY_SOUNDTRACK"}"
  HEADER_RG_FMT_SECONDARY_SPOKENWORD="${HEADER_RG_FMT_SECONDARY_SPOKENWORD:-"$RGV_FMT_SECONDARY_SPOKENWORD"}"
  HEADER_RG_FMT_SECONDARY_INTERVIEW="${HEADER_RG_FMT_SECONDARY_INTERVIEW:-"$RGV_FMT_SECONDARY_INTERVIEW"}"
  HEADER_RG_FMT_SECONDARY_AUDIOBOOK="${HEADER_RG_FMT_SECONDARY_AUDIOBOOK:-"$RGV_FMT_SECONDARY_AUDIOBOOK"}"
  HEADER_RG_FMT_SECONDARY_AUDIODRAMA="${HEADER_RG_FMT_SECONDARY_AUDIODRAMA:-"$RGV_FMT_SECONDARY_AUDIODRAMA"}"
  HEADER_RG_FMT_SECONDARY_LIVE="${HEADER_RG_FMT_SECONDARY_LIVE:-"$RGV_FMT_SECONDARY_LIVE"}"
  HEADER_RG_FMT_SECONDARY_REMIX="${HEADER_RG_FMT_SECONDARY_REMIX:-"$RGV_FMT_SECONDARY_REMIX"}"
  HEADER_RG_FMT_SECONDARY_DJMIX="${HEADER_RG_FMT_SECONDARY_DJMIX:-"$RGV_FMT_SECONDARY_DJMIX"}"
  HEADER_RG_FMT_SECONDARY_MIXTAPE="${HEADER_RG_FMT_SECONDARY_MIXTAPE:-"$RGV_FMT_SECONDARY_MIXTAPE"}"
  HEADER_RG_FMT_SECONDARY_DEMO="${HEADER_RG_FMT_SECONDARY_DEMO:-"$RGV_FMT_SECONDARY_DEMO"}"
  HEADER_RG_FMT_SECONDARY_FIELDREC="${HEADER_RG_FMT_SECONDARY_FIELDREC:-"$RGV_FMT_SECONDARY_FIELDREC"}"
  HEADER_RG_FMT_TITLE="${HEADER_RG_FMT_TITLE:-"$RGV_FMT_TITLE"}"
  HEADER_RG_FMT_ARTIST="${HEADER_RG_FMT_ARTIST:-"${CARTIST}%s${OFF}"}"
  HEADER_RG_FMT_YEAR="${HEADER_RG_FMT_YEAR:-"$RGV_FMT_YEAR"}"
  export HEADER_RG_FMT HEADER_RG_FMT_CNT HEADER_RG_FMT_RIGHTALIGN \
    HEADER_RG_FMT_FLAG_LOCAL HEADER_RG_FMT_FLAG_NO_LOCAL \
    HEADER_RG_FMT_TYPE_SINGLE HEADER_RG_FMT_TYPE_ALBUM HEADER_RG_FMT_TYPE_EP \
    HEADER_RG_FMT_TYPE_BROADCAST HEADER_RG_FMT_TYPE_OTHER \
    HEADER_RG_FMT_TYPE_UNKNOWN HEADER_RG_FMT_HASSECONDARY_YES \
    HEADER_RG_FMT_HASSECONDARY_NO HEADER_RG_FMT_SECONDARY \
    HEADER_RG_FMT_SECONDARY_COMPILATION HEADER_RG_FMT_SECONDARY_SOUNDTRACK \
    HEADER_RG_FMT_SECONDARY_SPOKENWORD HEADER_RG_FMT_SECONDARY_INTERVIEW \
    HEADER_RG_FMT_SECONDARY_AUDIOBOOK HEADER_RG_FMT_SECONDARY_AUDIODRAMA \
    HEADER_RG_FMT_SECONDARY_LIVE HEADER_RG_FMT_SECONDARY_REMIX \
    HEADER_RG_FMT_SECONDARY_DJMIX HEADER_RG_FMT_SECONDARY_MIXTAPE \
    HEADER_RG_FMT_SECONDARY_DEMO HEADER_RG_FMT_SECONDARY_FIELDREC \
    HEADER_RG_FMT_TITLE HEADER_RG_FMT_ARTIST HEADER_RG_FMT_YEAR

  # Header that displays the release (based on release view)
  HEADER_R_FMT="${HEADER_R_FMT:-"🎤\t<<artist>> 》<<title>> 〉<<tracks>> ${CRELINFO}tx${OFF} <<media>> | <<label>> <<country>> <<year>>"}"
  HEADER_R_FMT_CNT=$(($(printf "$HEADER_R_FMT" | tr -cd '\t' | wc -c) + 1))
  HEADER_R_FMT_RIGHTALIGN="${HEADER_R_FMT_RIGHTALIGN:-"1"}"
  HEADER_R_FMT_FLAG_LOCAL="${HEADER_R_FMT_FLAG_LOCAL:-"$RV_FMT_FLAG_LOCAL"}"
  HEADER_R_FMT_FLAG_NO_LOCAL="${HEADER_R_FMT_FLAG_NO_LOCAL:-"$RV_FMT_FLAG_NO_LOCAL"}"
  HEADER_R_FMT_STATUS_OFFICIAL="${HEADER_R_FMT_STATUS_OFFICIAL:-"$RV_FMT_STATUS_OFFICIAL"}"
  HEADER_R_FMT_STATUS_PROMO="${HEADER_R_FMT_STATUS_PROMO:-"$RV_FMT_STATUS_PROMO"}"
  HEADER_R_FMT_STATUS_BOOTLEG="${HEADER_R_FMT_STATUS_BOOTLEG:-"$RV_FMT_STATUS_BOOTLEG"}"
  HEADER_R_FMT_STATUS_PSEUDO="${HEADER_R_FMT_STATUS_PSEUDO:-"$RV_FMT_STATUS_PSEUDO"}"
  HEADER_R_FMT_STATUS_WITHDRAWN="${HEADER_R_FMT_STATUS_WITHDRAWN:-"$RV_FMT_STATUS_WITHDRAWN"}"
  HEADER_R_FMT_STATUS_EXPUNGED="${HEADER_R_FMT_STATUS_EXPUNGED:-"$RV_FMT_STATUS_EXPUNGED"}"
  HEADER_R_FMT_STATUS_CANCELLED="${HEADER_R_FMT_STATUS_CANCELLED:-"$RV_FMT_STATUS_CANCELLED"}"
  HEADER_R_FMT_STATUS_UNKNOWN="${HEADER_R_FMT_STATUS_UNKNOWN:-"$RV_FMT_STATUS_UNKNOWN"}"
  HEADER_R_FMT_TRACKS="${HEADER_R_FMT_TRACKS:-"${CRELINFO}%s${OFF}"}"
  HEADER_R_FMT_MEDIA="${HEADER_R_FMT_MEDIA:-"${CRELINFO}%s${OFF}"}"
  HEADER_R_FMT_YEAR="${HEADER_R_FMT_YEAR:-"${CRELINFO}%s${OFF}"}"
  HEADER_R_FMT_COUNTRY="${HEADER_R_FMT_COUNTRY:-"${CRELINFO}%s${OFF}"}"
  HEADER_R_FMT_LABEL="${HEADER_R_FMT_LABEL:-"${CRELINFO}%s${OFF}"}"
  HEADER_R_FMT_TITLE="${HEADER_R_FMT_TITLE:-"${CTITLE}%s${OFF}"}"
  HEADER_R_FMT_ARTIST="${HEADER_R_FMT_ARTIST:-"${CARTIST}%s${OFF}"}"
  export HEADER_R_FMT HEADER_R_FMT_CNT HEADER_R_FMT_RIGHTALIGN \
    HEADER_R_FMT_FLAG_LOCAL HEADER_R_FMT_FLAG_NO_LOCAL \
    HEADER_R_FMT_STATUS_OFFICIAL HEADER_R_FMT_STATUS_PROMO \
    HEADER_R_FMT_STATUS_BOOTLEG HEADER_R_FMT_STATUS_PSEUDO \
    HEADER_R_FMT_STATUS_WITHDRAWN HEADER_R_FMT_STATUS_EXPUNGED \
    HEADER_R_FMT_STATUS_CANCELLED HEADER_R_FMT_STATUS_UNKNOWN \
    HEADER_R_FMT_TRACKS HEADER_R_FMT_MEDIA HEADER_R_FMT_YEAR \
    HEADER_R_FMT_COUNTRY HEADER_R_FMT_LABEL HEADER_R_FMT_TITLE \
    HEADER_R_FMT_ARTIST

  # Artist Preview
  # ==============
  # Lines that contain the pattern defined in PREVIEW_NO_WRAP (see
  # `src/sh/preview.sh`) will not be wrapped.
  #
  # We distinguish between single-person and group artists.
  #
  # <<name>>           | string                   | Artist name
  # <<sortname>>       | string                   | Artist sort name
  # <<bio>>            | string                   | Artist biography
  # <<disambiguation>> | string                   | Artist disambiguation string
  # <<alias>>          | higher-order placeholder | Placeholder for aliases
  # <<start>           | higher-order placeholder | Placeholder for start string
  # <<end>>            | higher-order placeholder | Placeholder for end string
  # <<url>>            | higher-order placeholder | Placeholder for links
  PREVIEW_ARTIST_PERSON_FMT="${PREVIEW_ARTIST_PERSON_FMT:-"\n\n<<bio>><<alias>><<start>><<end>>\n<<url>>"}"
  PREVIEW_ARTIST_PERSON_NAME="${PREVIEW_ARTIST_PERSON_NAME:-"%s"}"
  PREVIEW_ARTIST_PERSON_SORTNAME="${PREVIEW_ARTIST_PERSON_SORTNAME:-"%s"}"
  PREVIEW_ARTIST_PERSON_BIO="${PREVIEW_ARTIST_PERSON_BIO:-"${CDESC}%s${OFF}\n\n"}"
  PREVIEW_ARTIST_PERSON_DISAMB="${PREVIEW_ARTIST_PERSON_DISAMB:-"%s"}"
  PREVIEW_ARTIST_PERSON_ALIAS="${PREVIEW_ARTIST_PERSON_ALIAS:-"${FAINT}Also known as ${ITALIC}%s${OFF}\n\n"}"
  PREVIEW_ARTIST_PERSON_ALIAS_JOIN="${PREVIEW_ARTIST_PERSON_ALIAS_JOIN:-"%s, %s"}"
  PREVIEW_ARTIST_PERSON_START="${PREVIEW_ARTIST_PERSON_START:-"🍼 Born: %s\n"}"
  PREVIEW_ARTIST_PERSON_START_FMT="${PREVIEW_ARTIST_PERSON_START_FMT:-"<<startdate>> <<startplace>>"}"
  PREVIEW_ARTIST_PERSON_START_STARTDATE="${PREVIEW_ARTIST_PERSON_START_STARTDATE:-"%s"}"
  PREVIEW_ARTIST_PERSON_START_STARTPLACE="${PREVIEW_ARTIST_PERSON_START_STARTPLACE:-"in %s"}"
  PREVIEW_ARTIST_PERSON_END="${PREVIEW_ARTIST_PERSON_END:-"🕯️ Died: %s\n"}"
  PREVIEW_ARTIST_PERSON_END_FMT="${PREVIEW_ARTIST_PERSON_END_FMT:-"<<enddate>> <<endplace>>"}"
  PREVIEW_ARTIST_PERSON_END_ENDDATE="${PREVIEW_ARTIST_PERSON_END_ENDDATE:-"%s"}"
  PREVIEW_ARTIST_PERSON_END_ENDPLACE="${PREVIEW_ARTIST_PERSON_END_ENDPLACE:-"in %s"}"
  PREVIEW_ARTIST_PERSON_URL="${PREVIEW_ARTIST_PERSON_URL:-"\n%s\n"}"
  PREVIEW_ARTIST_PERSON_URL_JOIN="${PREVIEW_ARTIST_PERSON_URL_JOIN:-"%s\n%s"}"
  PREVIEW_ARTIST_PERSON_URL_FMT="${PREVIEW_ARTIST_PERSON_URL_FMT:-"${PREVIEW_NO_WRAP}<<urlindex>>: <<urlname>> <<urllink>>\n"}"
  PREVIEW_ARTIST_PERSON_URL_URLINDEX="${PREVIEW_ARTIST_PERSON_URL_URLINDEX:-"${CDISAMB}%3d${OFF}"}"
  PREVIEW_ARTIST_PERSON_URL_URLNAME="${PREVIEW_ARTIST_PERSON_URL_URLNAME:-"${CDESC}%s${OFF}"}"
  PREVIEW_ARTIST_PERSON_URL_URLLINK="${PREVIEW_ARTIST_PERSON_URL_URLLINK:-"${FAINT}%s${OFF}"}"
  export PREVIEW_ARTIST_PERSON_FMT PREVIEW_ARTIST_PERSON_NAME \
    PREVIEW_ARTIST_PERSON_SORTNAME PREVIEW_ARTIST_PERSON_BIO \
    PREVIEW_ARTIST_PERSON_DISAMB PREVIEW_ARTIST_PERSON_ALIAS \
    PREVIEW_ARTIST_PERSON_ALIAS_JOIN PREVIEW_ARTIST_PERSON_START \
    PREVIEW_ARTIST_PERSON_START_FMT PREVIEW_ARTIST_PERSON_START_STARTDATE \
    PREVIEW_ARTIST_PERSON_START_STARTPLACE PREVIEW_ARTIST_PERSON_END \
    PREVIEW_ARTIST_PERSON_END_FMT PREVIEW_ARTIST_PERSON_END_ENDDATE \
    PREVIEW_ARTIST_PERSON_END_ENDPLACE PREVIEW_ARTIST_PERSON_URL \
    PREVIEW_ARTIST_PERSON_URL_JOIN PREVIEW_ARTIST_PERSON_URL_FMT \
    PREVIEW_ARTIST_PERSON_URL_URLINDEX PREVIEW_ARTIST_PERSON_URL_URLNAME \
    PREVIEW_ARTIST_PERSON_URL_URLLINK

  PREVIEW_ARTIST_GROUP_FMT="${PREVIEW_ARTIST_GROUP_FMT:-"$PREVIEW_ARTIST_PERSON_FMT"}"
  PREVIEW_ARTIST_GROUP_NAME="${PREVIEW_ARTIST_GROUP_NAME:-"$PREVIEW_ARTIST_PERSON_NAME"}"
  PREVIEW_ARTIST_GROUP_SORTNAME="${PREVIEW_ARTIST_GROUP_SORTNAME:-"$PREVIEW_ARTIST_PERSON_SORTNAME"}"
  PREVIEW_ARTIST_GROUP_BIO="${PREVIEW_ARTIST_GROUP_BIO:-"$PREVIEW_ARTIST_PERSON_BIO"}"
  PREVIEW_ARTIST_GROUP_DISAMB="${PREVIEW_ARTIST_GROUP_DISAMB:-"$PREVIEW_ARTIST_PERSON_DISAMB"}"
  PREVIEW_ARTIST_GROUP_ALIAS="${PREVIEW_ARTIST_GROUP_ALIAS:-"$PREVIEW_ARTIST_PERSON_ALIAS"}"
  PREVIEW_ARTIST_GROUP_ALIAS_JOIN="${PREVIEW_ARTIST_GROUP_ALIAS_JOIN:-"$PREVIEW_ARTIST_PERSON_ALIAS_JOIN"}"
  PREVIEW_ARTIST_GROUP_START="${PREVIEW_ARTIST_GROUP_START:-"✂️ Founded: %s\n"}"
  PREVIEW_ARTIST_GROUP_START_FMT="${PREVIEW_ARTIST_GROUP_START_FMT:-"$PREVIEW_ARTIST_PERSON_START_FMT"}"
  PREVIEW_ARTIST_GROUP_START_STARTDATE="${PREVIEW_ARTIST_GROUP_START_STARTDATE:-"$PREVIEW_ARTIST_PERSON_START_STARTDATE"}"
  PREVIEW_ARTIST_GROUP_START_STARTPLACE="${PREVIEW_ARTIST_GROUP_START_STARTPLACE:-"$PREVIEW_ARTIST_PERSON_START_STARTPLACE"}"
  PREVIEW_ARTIST_GROUP_END="${PREVIEW_ARTIST_GROUP_END:-"🛑 Dissolved: %s\n"}"
  PREVIEW_ARTIST_GROUP_END_FMT="${PREVIEW_ARTIST_GROUP_END_FMT:-"$PREVIEW_ARTIST_PERSON_END_FMT"}"
  PREVIEW_ARTIST_GROUP_END_ENDDATE="${PREVIEW_ARTIST_GROUP_END_ENDDATE:-"$PREVIEW_ARTIST_PERSON_END_ENDDATE"}"
  PREVIEW_ARTIST_GROUP_END_ENDPLACE="${PREVIEW_ARTIST_GROUP_END_ENDPLACE:-"$PREVIEW_ARTIST_PERSON_END_ENDPLACE"}"
  PREVIEW_ARTIST_GROUP_URL="${PREVIEW_ARTIST_GROUP_URL:-"$PREVIEW_ARTIST_PERSON_URL"}"
  PREVIEW_ARTIST_GROUP_URL_JOIN="${PREVIEW_ARTIST_GROUP_URL_JOIN:-"$PREVIEW_ARTIST_PERSON_URL_JOIN"}"
  PREVIEW_ARTIST_GROUP_URL_FMT="${PREVIEW_ARTIST_GROUP_URL_FMT:-"$PREVIEW_ARTIST_PERSON_URL_FMT"}"
  PREVIEW_ARTIST_GROUP_URL_URLINDEX="${PREVIEW_ARTIST_GROUP_URL_URLINDEX:-"$PREVIEW_ARTIST_PERSON_URL_URLINDEX"}"
  PREVIEW_ARTIST_GROUP_URL_URLNAME="${PREVIEW_ARTIST_GROUP_URL_URLNAME:-"$PREVIEW_ARTIST_PERSON_URL_URLNAME"}"
  PREVIEW_ARTIST_GROUP_URL_URLLINK="${PREVIEW_ARTIST_GROUP_URL_URLLINK:-"$PREVIEW_ARTIST_PERSON_URL_URLLINK"}"
  export PREVIEW_ARTIST_GROUP_FMT PREVIEW_ARTIST_GROUP_NAME \
    PREVIEW_ARTIST_GROUP_SORTNAME PREVIEW_ARTIST_GROUP_BIO \
    PREVIEW_ARTIST_GROUP_DISAMB PREVIEW_ARTIST_GROUP_ALIAS \
    PREVIEW_ARTIST_GROUP_ALIAS_JOIN PREVIEW_ARTIST_GROUP_START \
    PREVIEW_ARTIST_GROUP_START_FMT PREVIEW_ARTIST_GROUP_START_STARTDATE \
    PREVIEW_ARTIST_GROUP_START_STARTPLACE PREVIEW_ARTIST_GROUP_END \
    PREVIEW_ARTIST_GROUP_END_FMT PREVIEW_ARTIST_GROUP_END_ENDDATE \
    PREVIEW_ARTIST_GROUP_END_ENDPLACE PREVIEW_ARTIST_GROUP_URL \
    PREVIEW_ARTIST_GROUP_URL_JOIN PREVIEW_ARTIST_GROUP_URL_FMT \
    PREVIEW_ARTIST_GROUP_URL_URLINDEX PREVIEW_ARTIST_GROUP_URL_URLNAME \
    PREVIEW_ARTIST_GROUP_URL_URLLINK

  # Keybinding themes
  # =================
  # Format keybinding group
  KBF_GROUP="${KBF_GROUP:-"${UNDERLINE}${CKB}%s${OFF}"}"
  # Format key
  KBF_KEY="${KBF_KEY:-"${BOLD}${CKB}%s${OFF}"}"
  # Format description
  KBF_DESC="${KBF_DESC:-"${CKB}%s${OFF}"}"
  export KBF_GROUP KBF_KEY KBF_DESC

  # Playlist title and playlist store
  # =================================
  TITLE_PLYLST="${TITLE_PLYLST:-"  🎶 ${CARTIST}Playlist${OFF}  "}"
  TITLE_PLYLST_STORE="${TITLE_PLYLST_STORE:-"  🎶 ${CARTIST}Stored Playlists${OFF}  "}"
  # In the following %f is the file name
  PLYSTORE_PLAYLIST="${PLYSTORE_PLAYLIST:-"🎼 ${CPURPLE}%f${OFF}"}"
  export TITLE_PLYLST TITLE_PLYLST_STORE PLYSTORE_PLAYLIST

  # Lyrics
  # ======
  LYRICS_NO_LYRICS="${LYRICS_NO_LYRICS:-"(no lyrics)"}"
  export LYRICS_NO_LYRICS

  export THEME_LOADED=1
fi
